### ISSUE TITLE
Update D command help message

### ISSUE THREAD

**Issue by samuelfangjw** [AY2021S2-CS2103T-T11-2/tp#293]
<img width="756" alt="Screenshot 2021-04-04 at 12 13 37 AM" src="https://user-images.githubusercontent.com/60355570/113484389-a1025c80-94da-11eb-9a17-2cd49c938c20.png">

UpdateD doesn't show /by in example

**Comment by Eriksen2411** [comment]
/by is an optional parameter so no need in the example

**Comment by samuelfangjw** [comment]
the purpose of this example is to show how to use the command, not show that optional parameters are not allowed. the example used should showcase the whole command instead of just part of it.
