### ISSUE TITLE
Add Find Command

### ISSUE THREAD

**Issue by samuelfangjw** [AY2021S2-CS2103T-T11-2/tp#35]
As a user, I can find a person by name, so that I can locate details of persons without having to go through the entire list.

As a University Student, I want to find contacts by modules taken, so that I can easily find contacts who take the same module as me.

As a Student Teaching Assistant, I want to find contacts by tutorial group, so that I can easily find contacts of students in my class.

**Comment by Eriksen2411** [comment]
This issue no longer fits the project as the idea of project changed. Closed for ease of distraction.
