### ISSUE TITLE
Add a new contact feature

### ISSUE THREAD

**Issue by vevek** [AY2021S2-CS2103T-T11-2/tp#39]
As a busy university student, I can easily add new contacts so that I can keep track of details from peers I have crossed paths with.

**Comment by Eriksen2411** [comment]
This issue no longer fits the project as the idea of project changed. Closed for ease of distraction.

**Comment by Eriksen2411** [comment]
This issue no longer fits the project as the idea of project changed. Closed for ease of distraction.
