### ISSUE TITLE
Typo in About Us Page

### ISSUE THREAD

**Issue by samuelfangjw** [AY2021S2-CS2103T-T11-2/tp#49]
Should be Vevek instead of Vevel.
<img width="379" alt="Screenshot 2021-02-25 at 4 25 18 PM" src="https://user-images.githubusercontent.com/60355570/109124578-0e0d2e80-7786-11eb-9bb6-078d93d64182.png">

**Comment by vevek** [comment]
@samuelfangjw  Good catch 😂

**Comment by samuelfangjw** [comment]
@vevek XR claims credit for finding 😂

**Comment by vevek** [comment]
@samuelfangjw I think you've found the one 😂

**Comment by Eriksen2411** [comment]
Omg i just did it again. So sorry @vevek :)))
