### ISSUE TITLE
Update About Us page with team details

### ISSUE THREAD

**Issue by samuelfangjw** [AY2021S2-CS2103T-T11-2/tp#5]
- Add your own details. Include a suitable photo as described here.
- Including the the supervisor/lecturer is optional.
- The filename of the profile photo should be docs/images/githbub_username_in_lower_case.png. 
- Note the need for lower case e.g. JohnDoe123 -> docs/images/johndoe123.png not docs/images/JohnDoe123.png.
- If your photo is in jpg format, name the file as .png anyway.
- Indicate the different roles played and responsibilities held by each team member.
- You can reassign these roles and responsibilities (as explained in Admin  Project Scope) later in the project, if necessary.

**Comment by Eriksen2411** [comment]
#29
