### ISSUE TITLE
Remove whitespace in DeveloperGuide.md

### ISSUE THREAD

**Issue by samuelfangjw** [AY2021S2-CS2103T-T11-2/tp#52]
<img width="744" alt="Screenshot 2021-02-26 at 2 37 02 AM" src="https://user-images.githubusercontent.com/60355570/109200452-9833b200-77db-11eb-8c59-59824e4c6d84.png">

**Comment by vevek** [comment]
Are you able bring back the v1.1 milestone?

**Comment by samuelfangjw** [comment]
> Are you able bring back the v1.1 milestone?

can add to v1.1 (there is a closed tab when you click on milestones). if someone wants to do it now i think is ok to change the milestone to v1.1, else we can just throw it to next iteration.

**Comment by vevek** [comment]
@samuelfangjw Nice thanks. I'll get on it soon!
